# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: Update npm dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm run test

  deploy-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t nuxt-tripfixed .
      - run: docker save -o nuxt-tripfixed_image flystr
      - run: scp -o StrictHostKeyChecking=no nuxt-tripfixed_image root@159.69.150.31:~/flystr_image
      - run: ssh -o StrictHostKeyChecking=no  root@159.69.150.31 -- docker load -i nuxt-tripfixed_image
      - run: ssh -o StrictHostKeyChecking=no  root@159.69.150.31 -- docker-compose up -d
      - run: ssh -o StrictHostKeyChecking=no  root@159.69.150.31 -- docker image prune -af
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
